### PR TITLE
[esp-idf] migrate from ESP-IDF 3.3 to 4.0

### PR DESCRIPTION
**Pull request by erjiaqing**
The current vfs driver implement does not support ESP-IDF 4.0 or newer version, this PR fixes this.

### CODE REVIEW

**Comment by wgtdkp** [comment]
@erjiaqing Is the new implementation compatible with ESP-IDF 3.3? I think this project was based on ESP-IDF 3.3, should we also update the rest to support ESP-IDF 4.0 ?

**Comment by erjiaqing** [comment]
> @erjiaqing Is the new implementation compatible with ESP-IDF 3.3? I think this project was based on ESP-IDF 3.3, should we also update the rest to support ESP-IDF 4.0 ?

I used this code in project built with ESP-IDF 4.0, everything works fine, maybe I can try to update the tool chain to ESP-IDF 4.0

**Comment by wgtdkp** [comment]
> > @erjiaqing Is the new implementation compatible with ESP-IDF 3.3? I think this project was based on ESP-IDF 3.3, should we also update the rest to support ESP-IDF 4.0 ?
> 
> I used this code in project built with ESP-IDF 4.0, everything works fine, maybe I can try to update the tool chain to ESP-IDF 4.0

okay, if this project can work with ESP-IDF 4.0 by applying this PR, then I think it is fine to update it. You may need to update
1. The GitHub Action file in `.github` to build with IDF 4.0
2. document `example/README.md` to clone IDF `release/4.0`

**Review by wgtdkp — APPROVED** [review]
Thanks, LGTM 👍

**Review by jwhui — APPROVED** [review]

**Pull request merged**
